### ISSUE TITLE
warning: using map.field notation (without parentheses) - under Elixir 1.17

### ISSUE THREAD

**Issue by rob-vetspire** [beam-community/bamboo#669]
When running tests under Elixir 1.17 with `use Bamboo.Test` we get the following warning printed in test log:

```elixir
warning: using map.field notation (without parentheses) to invoke function 
Bamboo.TestAdapter.supports_attachments?() is deprecated, 
you must add parentheses instead: remote.function()
  (bamboo 2.3.0) lib/bamboo/mailer.ex:307: Bamboo.Mailer.validate_attachment_support/2
  (bamboo 2.3.0) lib/bamboo/mailer.ex:289: Bamboo.Mailer.validate_and_normalize/2
  (bamboo 2.3.0) lib/bamboo/mailer.ex:199: Bamboo.Mailer.deliver_now/4
  (bamboo 2.3.0) lib/bamboo/mailer.ex:231: Bamboo.Mailer.deliver_now!/4
 ```
 
 Fix required in `lib/bamboo/mailer.ex`: 
 
 change `supports_attachments?` 
 
 to `supports_attachments?()`

**Comment by doomspork** [comment]
@rob-vetspire PRs welcome!

**Comment by tonyrud** [comment]
Looks like this was fixed here: https://github.com/beam-community/bamboo/pull/664
